enum APIPath {
  signUp,
  login,
  getPlans,
  createProfile,
  getContentList,
  searchContent,
  addMyList,
  getList,
  getContentById,
  likeContent,
  addWatchTime,
  getVideo,
  getPaymentDetail,
  payPlanPayment,
  payRentalPayment,
  payRentalSeasonPayment,
  validateOTP,
  savePlan,
  removeContinueWatching,
  createRoom,
  getRoom,
  getRoomByUser,
  cancelRoom,
  deleteRoom,
  endRoom,
  getParticipants,
  addParticipants,
  leftRoom,
  approveParticipate,
  blockParticipate,
  updateRoom


}
